title: Vaibhav Kr Yadav
logo: "/assets/image/VaibhavKrYadav.jpg"
description: 
  Senior Software Engineer | Data Science Enthusiast
  <br><br>
  <a href="LinkedinUrl"> View My Linkedin Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
