title: Vaibhav Kr Yadav
logo: "/assets/image/VaibhavKrYadav.jpg?raw=true"
description: 
  Software Eng.|Data Science Enthusiast
  <br><br>
  <a href="LinkedinUrl"> View My Linkedin Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
