title: <p align= "center"> Vaibhav Kr Yadav </p>
logo: "/assets/image/VaibhavKrYadav.jpg?raw=true"
description: 
  Software Engineer|Data Science Enthusiast
  <br><br>
  <a href="LinkedinUrl"> View My Linkedin Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
